<?php
declare(strict_types=1); require dirname(__DIR__).'/app/bootstrap.php'; Auth::requireLogin();
$edit=null;
if(isset($_GET['edit'])){$st=$db->prepare('SELECT * FROM coaches WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch();}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'save';try{
if($action==='delete'){$db->prepare('DELETE FROM coaches WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Professor excluído.');}
else{$id=(int)($_POST['id']??0);$photo=upload_image('photo_path',$_POST['current_photo']?:null);$data=[trim($_POST['name']),trim($_POST['role_title']),trim($_POST['bio']),trim($_POST['phone']),trim($_POST['email']),$photo,isset($_POST['active'])?1:0,(int)$_POST['sort_order']];if($id){$data[]=$id;$db->prepare('UPDATE coaches SET name=?,role_title=?,bio=?,phone=?,email=?,photo_path=?,active=?,sort_order=? WHERE id=?')->execute($data);}else{$db->prepare('INSERT INTO coaches(name,role_title,bio,phone,email,photo_path,active,sort_order) VALUES(?,?,?,?,?,?,?,?)')->execute($data);}flash('success','Professor salvo.');}
}catch(Throwable $e){flash('danger',$e->getMessage());}redirect('coaches.php');}
$rows=$db->query('SELECT * FROM coaches ORDER BY sort_order,name')->fetchAll(); require __DIR__.'/_header.php'; ?>
<div class="page-title"><div><h1>Professores</h1><p>Cadastre a equipe técnica.</p></div></div><div class="admin-grid"><form method="post" enctype="multipart/form-data" class="panel form-stack"><?=csrf_field()?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=e((string)($edit['id']??''))?>"><input type="hidden" name="current_photo" value="<?=e($edit['photo_path']??'')?>"><h2><?=$edit?'Editar':'Novo'?> professor</h2><label>Nome<input name="name" value="<?=e($edit['name']??'')?>" required></label><label>Função<input name="role_title" value="<?=e($edit['role_title']??'')?>"></label><label>Biografia<textarea name="bio" rows="4"><?=e($edit['bio']??'')?></textarea></label><label>Telefone<input name="phone" value="<?=e($edit['phone']??'')?>"></label><label>E-mail<input type="email" name="email" value="<?=e($edit['email']??'')?>"></label><label>Foto<input type="file" name="photo_path" accept="image/*"></label><label>Ordem<input type="number" name="sort_order" value="<?=e((string)($edit['sort_order']??0))?>"></label><label class="check"><input type="checkbox" name="active" <?=($edit['active']??1)?'checked':''?>> Exibir no site</label><button class="btn primary">Salvar</button><?php if($edit):?><a class="btn" href="coaches.php">Cancelar</a><?php endif;?></form><div class="panel"><div class="table-wrap"><table><thead><tr><th>Nome</th><th>Função</th><th>Status</th><th>Ações</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['name'])?></td><td><?=e($r['role_title'])?></td><td><?=$r['active']?'Ativo':'Oculto'?></td><td class="actions"><a href="?edit=<?=$r['id']?>">Editar</a><form method="post" onsubmit="return confirm('Excluir este professor?')"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button>Excluir</button></form></td></tr><?php endforeach;?></tbody></table></div></div></div><?php require __DIR__.'/_footer.php'; ?>
