<?php
declare(strict_types=1);require dirname(__DIR__).'/app/bootstrap.php';Auth::requireLogin();
$teams=$db->query("SELECT id,name,badge_path,coach_name FROM teams WHERE active=1 ORDER BY name")->fetchAll();$coaches=$db->query("SELECT id,name FROM coaches WHERE active=1 ORDER BY name")->fetchAll();$athletes=$db->query("SELECT id,name,shirt_number FROM athletes WHERE active=1 ORDER BY name")->fetchAll();$comps=$db->query('SELECT id,name FROM competitions ORDER BY start_date DESC,name')->fetchAll();
$edit=null;if(isset($_GET['edit'])){$st=$db->prepare('SELECT * FROM matches WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch()?:null;}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$action=$_POST['action']??'save';
 if($action==='delete_match'){$db->prepare('DELETE FROM matches WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Partida excluída.');redirect('matches.php');}
 if($action==='delete_event'){$mid=(int)$_POST['match_id'];$db->prepare('DELETE FROM match_events WHERE id=? AND match_id=?')->execute([(int)$_POST['event_id'],$mid]);flash('success','Evento excluído.');redirect('matches.php?edit='.$mid.'#sumula');}
 if($action==='save_event'){
  $mid=(int)$_POST['match_id'];$eid=(int)($_POST['event_id']??0);
  $eventType=$_POST['event_type']??'gol';$side=$_POST['team_side']??'home';
  $participant=trim($_POST['participant_name']??'');$assist=trim($_POST['assist_name']??'');
  if($participant==='') throw new RuntimeException('Selecione ou informe o atleta do evento.');
  $period=$_POST['period']??'1';$minute=nullable_int($_POST['minute_mark']??null);
  $data=[null,$participant,null,$assist,$side,$eventType,$period,$minute,trim($_POST['event_notes']??'')];
  if($eid){$data[]=$eid;$data[]=$mid;$db->prepare('UPDATE match_events SET athlete_id=?,participant_name=?,assist_athlete_id=?,assist_name=?,team_side=?,event_type=?,period=?,minute_mark=?,notes=? WHERE id=? AND match_id=?')->execute($data);}
  else{$db->prepare('INSERT INTO match_events(match_id,athlete_id,participant_name,assist_athlete_id,assist_name,team_side,event_type,period,minute_mark,notes) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute(array_merge([$mid],$data));}
  flash('success','Evento da súmula salvo.');redirect('matches.php?edit='.$mid.'#sumula');
 }
 $id=(int)($_POST['id']??0);$date=$_POST['match_date']?str_replace('T',' ',$_POST['match_date']).':00':null;$homeId=nullable_int($_POST['home_team_id']);$awayId=nullable_int($_POST['away_team_id']);$home=trim($_POST['home_team']);$away=trim($_POST['away_team']);$homeLogo=upload_image('home_logo',($_POST['current_home_logo']??'')?:null);$awayLogo=upload_image('away_logo',($_POST['current_away_logo']??'')?:null);foreach($teams as $t){if($homeId===(int)$t['id']){$home=$t['name'];if(!$homeLogo)$homeLogo=$t['badge_path'];}if($awayId===(int)$t['id']){$away=$t['name'];if(!$awayLogo)$awayLogo=$t['badge_path'];}}
 $data=[nullable_int($_POST['competition_id']),$homeId,$awayId,$homeLogo,$awayLogo,$home,$away,$_POST['match_type'],nullable_int($_POST['coach_id']),trim($_POST['home_coach_name']),trim($_POST['away_coach_name']),$date,trim($_POST['location']),nullable_int($_POST['score_home']),nullable_int($_POST['score_away']),$_POST['status'],trim($_POST['notes'])];
 if($id){$data[]=$id;$db->prepare('UPDATE matches SET competition_id=?,home_team_id=?,away_team_id=?,home_logo_path=?,away_logo_path=?,home_team=?,away_team=?,match_type=?,coach_id=?,home_coach_name=?,away_coach_name=?,match_date=?,location=?,score_home=?,score_away=?,status=?,notes=? WHERE id=?')->execute($data);}else{$db->prepare('INSERT INTO matches(competition_id,home_team_id,away_team_id,home_logo_path,away_logo_path,home_team,away_team,match_type,coach_id,home_coach_name,away_coach_name,match_date,location,score_home,score_away,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute($data);$id=(int)$db->lastInsertId();}
 $db->prepare('DELETE FROM match_roster WHERE match_id=?')->execute([$id]);foreach(['home','away'] as $side){foreach(['starters'=>1,'reserves'=>0] as $field=>$starter){$names=preg_split('/\R/',trim($_POST[$side.'_'.$field]??''));foreach($names as $line){$line=trim($line);if($line==='')continue;$db->prepare("INSERT INTO match_roster(match_id,team_side,person_type,person_name,starter) VALUES(?,?,'atleta',?,?)")->execute([$id,$side,$line,$starter]);}}$coach=trim($_POST[$side.'_coach_name']??'');if($coach!=='')$db->prepare("INSERT INTO match_roster(match_id,team_side,person_type,person_name) VALUES(?,?,'tecnico',?)")->execute([$id,$side,$coach]);}
 flash('success','Partida salva.');redirect('matches.php?edit='.$id);
 }catch(Throwable $e){flash('danger',$e->getMessage());redirect('matches.php'.(!empty($_POST['id'])?'?edit='.(int)$_POST['id']:''));}}
$rows=$db->query('SELECT m.*,c.name competition_name FROM matches m LEFT JOIN competitions c ON c.id=m.competition_id ORDER BY match_date DESC,id DESC')->fetchAll();$events=[];$roster=['home'=>[],'away'=>[]];$eventEdit=null;if($edit){$st=$db->prepare('SELECT * FROM match_roster WHERE match_id=? ORDER BY team_side,person_type DESC,id');$st->execute([$edit['id']]);foreach($st->fetchAll() as $p)$roster[$p['team_side']][]=$p;$st=$db->prepare('SELECT me.*,COALESCE(a.name,me.participant_name) athlete_name,COALESCE(aa.name,me.assist_name) assist_display FROM match_events me LEFT JOIN athletes a ON a.id=me.athlete_id LEFT JOIN athletes aa ON aa.id=me.assist_athlete_id WHERE me.match_id=? ORDER BY me.period,me.minute_mark,id');$st->execute([$edit['id']]);$events=$st->fetchAll();if(isset($_GET['event']))foreach($events as $ev)if((int)$ev['id']===(int)$_GET['event'])$eventEdit=$ev;}
require __DIR__.'/_header.php';?>
<div class="page-title"><div><h1>Partidas</h1><p>Cadastro organizado, times, relacionados, placar e súmula completa.</p></div><?php if($edit):?><a class="btn" href="matches.php">Nova partida</a><?php endif;?></div>
<?php if(!$edit):?><div class="panel"><div class="table-wrap"><table><thead><tr><th>Data</th><th>Confronto</th><th>Competição</th><th>Local</th><th>Ações</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=format_date($r['match_date'],true)?></td><td><div class="admin-score-line"><span><?=e($r['home_team'])?> <b><?=e((string)($r['score_home']??''))?></b></span><i>x</i><span><b><?=e((string)($r['score_away']??''))?></b> <?=e($r['away_team'])?></span></div></td><td><?=e($r['competition_name']??ucfirst(str_replace('_',' ',$r['match_type'])))?></td><td><?=e($r['location'])?></td><td class="actions"><a href="?edit=<?=$r['id']?>">Editar / súmula</a><form method="post" onsubmit="return confirm('Excluir esta partida?')"><?=csrf_field()?><input type="hidden" name="action" value="delete_match"><input type="hidden" name="id" value="<?=$r['id']?>"><button>Excluir</button></form></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;?>
<form method="post" enctype="multipart/form-data" class="panel match-editor"><?=csrf_field()?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=e((string)($edit['id']??''))?>"><input type="hidden" name="current_home_logo" value="<?=e($edit['home_logo_path']??'')?>"><input type="hidden" name="current_away_logo" value="<?=e($edit['away_logo_path']??'')?>"><h2><?=$edit?'Editar':'Nova'?> partida</h2><div class="form-grid"><label>Competição<select name="competition_id"><option value="">Sem competição</option><?php foreach($comps as $c):?><option value="<?=$c['id']?>" <?=($edit['competition_id']??null)==$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select></label><label>Tipo<select name="match_type"><?php foreach(['competicao'=>'Competição','amistoso'=>'Amistoso','jogo_treino'=>'Jogo-treino'] as $v=>$l):?><option value="<?=$v?>" <?=($edit['match_type']??'competicao')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label>Data e hora<input type="datetime-local" name="match_date" value="<?=!empty($edit['match_date'])?e(date('Y-m-d\TH:i',strtotime($edit['match_date']))):''?>"></label><label>Local<input name="location" value="<?=e($edit['location']??'')?>"></label></div>
<div class="teams-editor"><section><h3>Mandante (casa)</h3><label>Time cadastrado<select name="home_team_id"><option value="">Outro time</option><?php foreach($teams as $t):?><option value="<?=$t['id']?>" <?=($edit['home_team_id']??null)==$t['id']?'selected':''?>><?=e($t['name'])?></option><?php endforeach;?></select></label><label>Nome<input name="home_team" value="<?=e($edit['home_team']??'Titans Academy Futebol')?>" required></label><label>Logo<input type="file" name="home_logo" accept="image/*"></label><?php if(!empty($edit['home_logo_path'])):?><img class="team-logo-preview" src="../<?=e($edit['home_logo_path'])?>"><?php endif;?><label>Técnico<input name="home_coach_name" value="<?=e($edit['home_coach_name']??'')?>"></label><div class="roster-editor-grid"><label>Relacionados / titulares <small>Um atleta por linha</small><textarea name="home_starters" rows="8"><?php foreach($roster['home'] as $p)if($p['person_type']==='atleta' && (int)$p['starter']===1)echo e($p['person_name'])."\n";?></textarea></label><label>Banco de reservas <small>Um atleta por linha</small><textarea name="home_reserves" rows="8"><?php foreach($roster['home'] as $p)if($p['person_type']==='atleta' && (int)$p['starter']===0)echo e($p['person_name'])."\n";?></textarea></label></div></section><div class="match-score"><input type="number" min="0" name="score_home" value="<?=e((string)($edit['score_home']??''))?>"><b>x</b><input type="number" min="0" name="score_away" value="<?=e((string)($edit['score_away']??''))?>"></div><section><h3>Visitante</h3><label>Time cadastrado<select name="away_team_id"><option value="">Outro time</option><?php foreach($teams as $t):?><option value="<?=$t['id']?>" <?=($edit['away_team_id']??null)==$t['id']?'selected':''?>><?=e($t['name'])?></option><?php endforeach;?></select></label><label>Nome<input name="away_team" value="<?=e($edit['away_team']??'')?>" required></label><label>Logo<input type="file" name="away_logo" accept="image/*"></label><?php if(!empty($edit['away_logo_path'])):?><img class="team-logo-preview" src="../<?=e($edit['away_logo_path'])?>"><?php endif;?><label>Técnico<input name="away_coach_name" value="<?=e($edit['away_coach_name']??'')?>"></label><div class="roster-editor-grid"><label>Relacionados / titulares <small>Um atleta por linha</small><textarea name="away_starters" rows="8"><?php foreach($roster['away'] as $p)if($p['person_type']==='atleta' && (int)$p['starter']===1)echo e($p['person_name'])."\n";?></textarea></label><label>Banco de reservas <small>Um atleta por linha</small><textarea name="away_reserves" rows="8"><?php foreach($roster['away'] as $p)if($p['person_type']==='atleta' && (int)$p['starter']===0)echo e($p['person_name'])."\n";?></textarea></label></div></section></div>
<div class="form-grid"><label>Status<select name="status"><?php foreach(['agendada','realizada','cancelada'] as $v):?><option value="<?=$v?>" <?=($edit['status']??'agendada')===$v?'selected':''?>><?=ucfirst($v)?></option><?php endforeach;?></select></label><label class="full">Observações<textarea name="notes" rows="3"><?=e($edit['notes']??'')?></textarea></label></div><button class="btn primary">Salvar partida</button></form>
<?php if($edit):?>
<div class="panel" id="sumula">
  <div class="panel-head"><div><h2>Súmula</h2><p>Selecione primeiro o clube. Depois registre o evento, o atleta, o tempo e o minuto.</p></div></div>
  <?php
    $rosterJson=['home'=>['starters'=>[],'reserves'=>[]],'away'=>['starters'=>[],'reserves'=>[]]];
    foreach(['home','away'] as $side) foreach($roster[$side] as $person) if($person['person_type']==='atleta') $rosterJson[$side][(int)$person['starter']===1?'starters':'reserves'][]=$person['person_name'];
  ?>
  <form method="post" class="sumula-card" id="sumulaForm" data-roster='<?=e(json_encode($rosterJson,JSON_UNESCAPED_UNICODE))?>'>
    <?=csrf_field()?><input type="hidden" name="action" value="save_event"><input type="hidden" name="match_id" value="<?=$edit['id']?>"><input type="hidden" name="event_id" value="<?=e((string)($eventEdit['id']??''))?>">
    <div class="sumula-row first-row">
      <label>Clube<select name="team_side" id="eventTeam"><option value="home" <?=($eventEdit['team_side']??'home')==='home'?'selected':''?>><?=e($edit['home_team'])?></option><option value="away" <?=($eventEdit['team_side']??'')==='away'?'selected':''?>><?=e($edit['away_team'])?></option></select></label>
      <label>Evento<select name="event_type" id="eventType"><?php foreach(['gol'=>'Gol','assistencia'=>'Assistência','cartao_amarelo'=>'Cartão amarelo','cartao_vermelho'=>'Cartão vermelho','substituicao'=>'Substituição'] as $v=>$l):$selected=($eventEdit['event_type']??'gol');if(str_starts_with($selected,'substituicao_'))$selected='substituicao';?><option value="<?=$v?>" <?=$selected===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label>
      <label>Tempo<select name="period"><option value="1" <?=($eventEdit['period']??'1')==='1'?'selected':''?>>1º tempo</option><option value="2" <?=($eventEdit['period']??'')==='2'?'selected':''?>>2º tempo</option><option value="extra" <?=($eventEdit['period']??'')==='extra'?'selected':''?>>Prorrogação</option></select></label>
      <label>Minuto<input type="number" min="0" max="130" name="minute_mark" value="<?=e((string)($eventEdit['minute_mark']??''))?>" placeholder="Ex.: 23"></label>
    </div>
    <div class="sumula-row normal-event" id="normalEventFields">
      <label>Atleta<select id="primaryAthlete"><option value="">Selecione</option></select></label>
      <label>Ou digite o nome<input id="primaryManual" value="<?=e($eventEdit['participant_name']??'')?>" placeholder="Nome do atleta"></label>
      <label class="assist-field">Assistência<select id="assistAthlete"><option value="">Sem assistência</option></select></label>
      <label class="assist-field">Ou digite a assistência<input id="assistManual" value="<?=e($eventEdit['assist_name']??'')?>" placeholder="Nome do assistente"></label>
    </div>
    <div class="substitution-fields" id="substitutionFields">
      <div class="sub-box"><h3>Atleta que sai</h3><label>Relacionados em campo<select id="subOut"><option value="">Selecione o atleta</option></select></label><label>Ou digite manualmente<input id="subOutManual" placeholder="Nome do atleta que sai"></label></div>
      <div class="sub-box"><h3>Atleta que entra</h3><label>Banco de reservas<select id="subIn"><option value="">Selecione o reserva</option></select></label><label>Ou digite manualmente<input id="subInManual" placeholder="Nome do atleta que entra"></label></div>
    </div>
    <input type="hidden" name="participant_name" id="participantName"><input type="hidden" name="assist_name" id="assistName"><input type="hidden" name="event_type" id="savedEventType">
    <label class="event-notes">Observação<input name="event_notes" value="<?=e($eventEdit['notes']??'')?>" placeholder="Informação complementar (opcional)"></label>
    <div class="sumula-actions"><button class="btn primary"><?=$eventEdit?'Atualizar':'Adicionar'?> evento</button><?php if($eventEdit):?><a class="btn" href="matches.php?edit=<?=$edit['id']?>#sumula">Cancelar edição</a><?php endif;?></div>
  </form>
  <div class="table-wrap mt"><table><thead><tr><th>Tempo</th><th>Min.</th><th>Evento</th><th>Atleta</th><th>Relacionado</th><th>Time</th><th>Ações</th></tr></thead><tbody><?php foreach($events as $ev):?><tr><td><?=e(($ev['period']??'1')==='1'?'1º':(($ev['period']??'')==='2'?'2º':'Extra'))?></td><td><?=e((string)$ev['minute_mark'])?></td><td><?=e(str_replace('_',' ',$ev['event_type']))?></td><td><?=e($ev['athlete_name']??'—')?></td><td><?=e($ev['assist_display']??'—')?></td><td><?=$ev['team_side']==='home'?e($edit['home_team']):e($edit['away_team'])?></td><td class="actions"><a href="?edit=<?=$edit['id']?>&event=<?=$ev['id']?>#sumula">Editar</a><form method="post" onsubmit="return confirm('Excluir evento?')"><?=csrf_field()?><input type="hidden" name="action" value="delete_event"><input type="hidden" name="match_id" value="<?=$edit['id']?>"><input type="hidden" name="event_id" value="<?=$ev['id']?>"><button>Excluir</button></form></td></tr><?php endforeach;?></tbody></table></div>
</div>
<script>
(()=>{const form=document.getElementById('sumulaForm');if(!form)return;const roster=JSON.parse(form.dataset.roster||'{}'),team=document.getElementById('eventTeam'),type=document.getElementById('eventType');
const fill=(el,items,first)=>{el.innerHTML='<option value="">'+first+'</option>'+items.map(n=>'<option value="'+String(n).replace(/"/g,'&quot;')+'">'+n+'</option>').join('')};
const refresh=()=>{const r=roster[team.value]||{starters:[],reserves:[]};fill(document.getElementById('primaryAthlete'),[...r.starters,...r.reserves],'Selecione');fill(document.getElementById('assistAthlete'),[...r.starters,...r.reserves],'Sem assistência');fill(document.getElementById('subOut'),r.starters,'Selecione o atleta');fill(document.getElementById('subIn'),r.reserves,'Selecione o reserva');toggle()};
const toggle=()=>{const sub=type.value==='substituicao';document.getElementById('normalEventFields').style.display=sub?'none':'grid';document.getElementById('substitutionFields').style.display=sub?'grid':'none';document.querySelectorAll('.assist-field').forEach(x=>x.style.display=type.value==='gol'?'grid':'none')};team.addEventListener('change',refresh);type.addEventListener('change',toggle);refresh();
form.addEventListener('submit',e=>{const sub=type.value==='substituicao';let primary,assist;if(sub){primary=document.getElementById('subOutManual').value.trim()||document.getElementById('subOut').value;assist=document.getElementById('subInManual').value.trim()||document.getElementById('subIn').value;document.getElementById('savedEventType').value='substituicao_saida';if(!primary||!assist){e.preventDefault();alert('Informe o atleta que sai e o atleta que entra.');return;}}else{primary=document.getElementById('primaryManual').value.trim()||document.getElementById('primaryAthlete').value;assist=document.getElementById('assistManual').value.trim()||document.getElementById('assistAthlete').value;document.getElementById('savedEventType').value=type.value;if(!primary){e.preventDefault();alert('Selecione ou informe o atleta.');return;}}document.getElementById('participantName').value=primary;document.getElementById('assistName').value=assist;});})();
</script>
<?php endif;?>
<?php require __DIR__.'/_footer.php';?>
